- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Enable nginx
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Copy nginx config for authentik
  template:
    src: auth.conf.j2
    dest: /etc/nginx/sites-available/auth.conf

- name: Enable site
  file:
    src: /etc/nginx/sites-available/auth.conf
    dest: /etc/nginx/sites-enabled/auth.conf
    state: link

- name: Copy nginx config for DNS
  template:
    src: dns.conf.j2
    dest: /etc/nginx/sites-available/dns.conf

- name: Enable DNS site
  file:
    src: /etc/nginx/sites-available/dns.conf
    dest: /etc/nginx/sites-enabled/dns.conf
    state: link

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted