services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    network_mode: host

    env_file:
      - .env

    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}

    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    restart: unless-stopped